// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACsR-3fcmmkzIYwqxKV0Zx80okKp0NNLw',
    appId: '1:306538288927:web:631e279def3129b0b8022a',
    messagingSenderId: '306538288927',
    projectId: 'air-projekt-bamboo',
    authDomain: 'air-projekt-bamboo.firebaseapp.com',
    databaseURL: 'https://air-projekt-bamboo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-projekt-bamboo.appspot.com',
    measurementId: 'G-CQTEECR8C8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxe3gE2LatxTVF5lW_5sevRlLCIVsDl0w',
    appId: '1:306538288927:android:fc258e16bafb02d4b8022a',
    messagingSenderId: '306538288927',
    projectId: 'air-projekt-bamboo',
    databaseURL: 'https://air-projekt-bamboo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-projekt-bamboo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKzYfv7u3DbT4dQT7RGp3Zceqd7T8LJS0',
    appId: '1:306538288927:ios:870445b784b4afccb8022a',
    messagingSenderId: '306538288927',
    projectId: 'air-projekt-bamboo',
    databaseURL: 'https://air-projekt-bamboo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-projekt-bamboo.appspot.com',
    iosClientId: '306538288927-ro22cr8l07kc24pkevofm26kgbcf04df.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDKzYfv7u3DbT4dQT7RGp3Zceqd7T8LJS0',
    appId: '1:306538288927:ios:870445b784b4afccb8022a',
    messagingSenderId: '306538288927',
    projectId: 'air-projekt-bamboo',
    databaseURL: 'https://air-projekt-bamboo-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'air-projekt-bamboo.appspot.com',
    iosClientId: '306538288927-ro22cr8l07kc24pkevofm26kgbcf04df.apps.googleusercontent.com',
    iosBundleId: 'com.example.testApp',
  );
}
